improved ngrx docs
onecx/docs-guides-angular pull request #3
Opened 2024-07-01 11:40 UTC by SchettlerKoehler

2024-07-02 08:17 UTC, BenjaminPabst commented on docs/modules/angular/pages/ngrx/ngrx.adoc
> +│   │   │    │    │     ├── page1subcomponent1    // one of subcomponent for page, optional + might have many of them, this can also be a dialog that is only used by this pages
dialogs should be in a subfolder (page1/dialogs/dialog1...) to better structure the files

2024-07-03 07:47 UTC, anninowak requested changes
Hi Jan, anbei meine Anmerkungen.

2024-07-03 07:47 UTC, anninowak commented on docs/modules/angular/pages/ngrx/ngrx.adoc
> +│   │   │    │    ├── page1       // each pages gets a subfolder, might have many of them
each page / every page gets
oder 
all pages get

2024-07-03 07:47 UTC, anninowak commented on docs/modules/angular/pages/ngrx/ngrx.adoc
> +│   │   │    │    │     ├── dialog1subcomponent1    // one of subcomponent for page, optional + might have many of them
subcomponent for page or dialog?

2024-07-03 07:47 UTC, anninowak commented on docs/modules/angular/pages/ngrx/ngrx.adoc
> +Both dialog types have in common that
that:

2024-07-03 07:47 UTC, anninowak commented on docs/modules/angular/pages/ngrx/ngrx.adoc
> +* they are communicating with the opener of the dialog by implementing `DialogResult`
Was meinst du genau mit dem Opener vom Dialog?

2024-07-03 07:47 UTC, anninowak commented on docs/modules/angular/pages/ngrx/ngrx.adoc
> +The components of this dialogs are subcomponents of the page they are used in. The subcomponents are placed in a subfolder called 'dialogs'. They do not have a septate section in the store because th
this dialog
oder 
these dialogs

2024-07-03 07:47 UTC, anninowak commented on docs/modules/angular/pages/ngrx/ngrx.adoc
> +The components of this dialogs are subcomponents of the page they are used in. The subcomponents are placed in a subfolder called 'dialogs'. They do not have a septate section in the store because th
They do not have a septate section
--> separate ?

2024-07-03 07:47 UTC, anninowak commented on docs/modules/angular/pages/ngrx/ngrx.adoc
> +The components of this dialogs are subcomponents of the page they are used in. The subcomponents are placed in a subfolder called 'dialogs'. They do not have a septate section in the store because th
The viewmodel is read from the store via a viewmodel selector in the effects or _is_ build with data from the action which is triggering the opening of the dialog.

2024-07-03 07:47 UTC, anninowak commented on docs/modules/angular/pages/ngrx/ngrx.adoc
> +This type of dialog is always dispatching an action that is informing about the opening of the dialog in the constructor of the dialog component. The viewmodel is read from the store via a selector l
Meinst du einen bestimmten DialogTyp hier? (mit this type of dialog)?

2024-07-03 11:07 UTC, merged